exclude: '.*\.key'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: https://github.com/frnmst/md-toc
  rev: 8.2.3  # or a specific git tag from md-toc
  hooks:
  - id: md-toc
    args: [-p, github]
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs

# Too restrictive
# - repo: https://github.com/johnfraney/flake8-markdown
#   rev: v0.2.0
#   hooks:
#     - id: flake8-markdown
